### ISSUE TITLE
expected string or buffer

### ISSUE THREAD

**Issue by fridholm** [jadu/sublime-behat-completions#1]
I got this in my console when I tried to use it

My settings looks like this:
{
    "behat_executable_path": "/Users/<my_user>/vendor/bin/behat",
    "behat_config_path": "/Users/<my_user>/vendor/behat/behat/behat.yml"
}

I used those paths, since I don't really want a separate config for every project just now.

I use it in conjunction with the behat syntax package.

And the error:

Traceback (most recent call last):
  File "./sublime_plugin.py", line 362, in run_
  File "./Behat Completions.py", line 25, in run
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/re.py", line 151, in sub
    return _compile(pattern, 0).sub(repl, string, count)
TypeError: expected string or buffer

I get this error when the syntax i set to behat, but not when it is set to plain text.

**Comment by fridholm** [comment]
Well it works with the gherkin syntax, so I suppose I can use that as a replacement...
